version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    vendor: true
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
